### ISSUE TITLE
SHA256withECDSA vs ECDSAwithSHA256

### ISSUE THREAD

**Issue by danvangeest** [lamps-wg/draft-composite-sigs#14]
I'm curious why in the "Composite Signature Algorithms" table, SHA256withECDSA for example is used instead of ECDSAwithSHA256? Isn't the latter more commonly used terminology?

**Comment by johngray-dev** [comment]
In July 3rd, Jan said he would update the table.

**Comment by janklaussner** [comment]
updated the naming in the table in PR#16

**Comment by johngray-dev** [comment]
Confirmed that Jan resolved this in #16
