### ISSUE TITLE
Read Carl's email

### ISSUE THREAD

**Issue by ounsworth** [lamps-wg/draft-composite-sigs#20]
See https://mailarchive.ietf.org/arch/msg/spasm/b7rvHiKnA80oZ-VqQY7LIoFdsu8/. The point below is the that using a template like this with an embedded ASN.1 definition causes compilers (or at least the compiler I use) to emit far more code than if the structure were factored out of the template definition. I’ve not spent any time with composite-kem yet, but it looks like some of the comments I had relative to the composite-signatures draft would apply here too.

**Comment by johngray-dev** [comment]
This work was done in composite signatures, now the composite KEM draft needs to also be updated.

**Comment by johngray-dev** [comment]
This work was completed in signatures.
