### ISSUE TITLE
Make RSA 4096 combos

### ISSUE THREAD

**Issue by ounsworth** [lamps-wg/draft-composite-sigs#24]
We have been asked to add RSA-4096 combos for existing infrastructures where deployed software or policy requires 4096 bit keys.

Suggestion is that since RSA 4096 is not much above 128 bit security (certainly not as much as AES-192 or SHA-384), we should pair it with the same cipher suites as the RSA-3072 combo. Or maybe even replace the 3072 combo?

**Comment by janklaussner** [comment]
@ounsworth I would rather add combinations, and yes, the same as with RSA 3072.
1. RSA 4096 is expensive when I think of our smart card products
2. RSA 3072 is expected to be secure enough *at least* till 2030 by BSI
3. not even RSA 1024 is cracked till now (80 bits security) so I expect it to last 10 more years... without CRQC of course

**Comment by ounsworth** [comment]
**Should we drop the key size from the OID at all?**

Yes: Piotr, Scott
No: Tim, Sophie, Mike

**Comment by johngray-dev** [comment]
Group decided to add two new RSA 4096 combinations... one for PKCS 1.5, and PSS...

**Comment by johngray-dev** [comment]
We decided to add these combinations:  

MLDSA65-RSA4096-PKCS15-SHA512
MLDSA65-RSA4096-PSS-SHA512

We decided to keep the RSA keysize in the OID definiton

**Comment by johngray-dev** [comment]
closes #23

**Comment by johngray-dev** [comment]
Didn't mean to close

**Comment by johngray-dev** [comment]
4096 combinations added in pull #51  - Closing this ticket
