### ISSUE TITLE
Add back text to not reuse component keys

### ISSUE THREAD

**Issue by ounsworth** [lamps-wg/draft-composite-sigs#25]
For the security proofs, it is imperative that the RSA / ECC keys be generated fresh for the composite and not re-used from existing deployments. I swear we had text to this effect. Certainly this deserves its own Security Consideration section.

**Comment by danvangeest** [comment]
In draft-ietf-lamps-pq-composite-sigs-02, you have the following text:

Section 4.1:
   Compliant parties MUST NOT use or import component keys that are used
   in other contexts, combinations, or by themselves (i.e., not only in
   X.509 certificates).

Section 5.2:
   Component keys of a CompositeSignaturePublicKey MUST NOT be used in
   any other type of key or as a standalone key.

Section 5.3:
   Component keys of a CompositeSignaturePrivateKey MUST NOT be used in
   any other type of key or as a standalone key.

I agree this should be more prominent, and in the Security Considerations section, with reference to the proofs.

Do you have a reference to the security proofs which make this imperative, which you could link here (for my own curiousity)?  Is this just related to Weak Non-Separability where if you reuse the component signature keys then you open yourself up to downgrade/stripping attacks, and if you don't reuse them then you cut off those attacks?  Or is the reuse forbidden for a more fundamental security reason, even if you use WNS artifacts in your composite scheme?

**Comment by danvangeest** [comment]
Ah I see that I am reading my emails out of order and this PR came from here: https://mailarchive.ietf.org/arch/msg/spasm/Ab7_g1Q3mVMCZH_GXiDLb-7dxVw/

However, that thread is about composite KEM so I wonder if the same security concerns about simultaneous creation/combined usage also apply to composite signatures?

**Comment by johngray-dev** [comment]
We added a very detailed section on Key re-use in the security considerations section.   I will add a reference to this section in the 3 sections about that mention key re-use.   

   "For more details on the security considerations around key reuse, see section {sec-cons-key-reuse}"

**Comment by johngray-dev** [comment]
Added references to the security considerations key reuse section in pull #72
