### ISSUE TITLE
We should be clear about which non-separability level we acheive

### ISSUE THREAD

**Issue by ounsworth** [lamps-wg/draft-composite-sigs#27]
Add a reference to draft-ietf-pquip-hybrid-signature-spectrums, and be clear (possibly with a full security consideration section) about which level this is achieving.

**Comment by ounsworth** [comment]
Potential text:

> My understanding (without talking with my co-authors) is that inclusion of a composite signature algorithm OID inside a signed message achieved “Weak Non-Separability”, but that when you consider that within PKI, the verifier has the verification public key within a certificate, and that re-use of public keys between composite and non-composite certificates is forbidden, then all together this achieves “Strong Non-Separability”.

**Comment by johngray-dev** [comment]
Extensive text in the Security considerations section was added regarding non separability.  This issue is resolved.
