### ISSUE TITLE
Description of "PUBLIC-KEY" is wrong

### ISSUE THREAD

**Issue by ounsworth** [lamps-wg/draft-composite-sigs#44]
Laurent Pion points out that a signature is produced by a private key, not a public key.

> Chapter 6.1, table 1
> Don’t know if it’s my wrong understanding or a little mistake, PUBLIC-KEYS, is it the composite (private) key required to produce the signature or the public key to verify it?

https://mailarchive.ietf.org/arch/msg/spasm/S5CyDKP4xngRmHNdlmHozXrpLzw/

**Comment by johngray-dev** [comment]
Fixed as part of #59
