### ISSUE TITLE
Adjust Security Consideration on stripping attacks

### ISSUE THREAD

**Issue by ounsworth** [lamps-wg/draft-composite-sigs#46]
In response to comments from Falko:

https://mailarchive.ietf.org/arch/msg/spasm/-wg0a8xuhrosRdZlzvQpYD1r0vE/

OLD
> When considering stripping attacks, one need consider the case where an attacker has fully compromised one of the component algorithms to the point that they can produce forged signatures that appear valid under one of the component public keys, and thus fool a victim verifier into accepting a forged signature.

NEW

> Hybrid signature primitives that are susceptible to stripping attacks violate existential universal forgery by virtue of the fact that the signer produced (\sigma, M) where \sigma = {\sigma_mldsa, \sigma_trad}, and thus the ability to produce from this valid pairs (\sigma_mldsa, M) or (\sigma_trad, M) would constitute existential forgery attacks under the definition of EUF. This could be turned into practical attacks in a number of ways, such as a “signature mis-attribution attack” where the attacker makes a message appear to be signed by a certificate containing the public key {RSA} when in fact it was signed by the public key {ML-DSA, RSA} which happens to share the RSA public key but may in fact belong to a completely different entity. On top of this, a stripping attack isolates the two algorithms, which could lead to still further message forgery attacks against the weaker of the two algorithms.

(I don’t have the I-D text in front of me right now, so I’ll probably need to adjust it a bit to fit with the section’s flow.)

**Comment by codespree** [comment]
# Chained Signature Idea

Though this may or may not not address stripping attacks, I am just adding it here for your consideration as an idea:

```
dom_sep(alg1, alg2):
    return oid_to_der(alg1.oid) || oid_to_der(alg2.oid)

pre_hash(alg1, alg2, msg):
    return dom_sep(alg1, alg2) || hash(msg)

sign(alg1, alg2, sk_alg_1, sk_alg_2, msg):
    // Signing order alg1, alg2 chained
    // Original signature on msg with alg 1 using composite domain separator (alg1, alg2)
    s1 = alg1.sign(sk_alg_1 , pre_hash(alg1, alg2, msg))

    // Signature on s1 with alg 2 using opposite composite  domain separator (alg2, alg1)
    s1' = alg2.sign(sk_alg_2 , pre_hash(alg2, alg1, s1))

    // Signing order alg2, alg1 chained
    // Original signature on msg with alg2 using composite domain separator (alg2, alg1)
    s2 = alg2.sign(sk_alg_2, pre_hash(alg2, alg1, msg))
     
    // Signature on s2 with alg 1 with opposite composite  domain separator (alg1, alg2)
    s2' = alg1.sign(sk_alg_1, pre_hash(alg1, alg2, s2)
    
    return comp_sig(s1, s1', s2, s2')

verify(alg1, alg2, pk_alg1, pk_alg2, comp_sig, msg):
    s1 = comp_sig[0]
    s1' = comp_sig[1]
    s2 = comp_sig[2]
    s2' = comp_sig[3]

    // Verification of signature s1 on original message with alg1
    u1 = alg1.verify(pk_alg_1 , s1, pre_hash(alg1, alg2, msg))
    // Verification of signature s1' on message s1 with alg 2
    u1' = alg2. verify(pk_alg_2 , s1', pre_hash(alg2, alg1, s1))
    
    // Verification of signature s2 on original message with alg2
    v2 = alg2.verify(pk_alg_2, s2, pre_hash(alg2, alg1, msg))
    // Verification of signature s2' on message s2 with alg1
    v2' = alg1.verify(pk_alg_1, s2', pre_hash(alg2, alg1, s2)
    
    return u1 && u1' && v2 && v2'
```
