### ISSUE TITLE
Security consideration: do we mention the revocation problem?

### ISSUE THREAD

**Issue by ounsworth** [lamps-wg/draft-composite-sigs#49]
We should mention that when a CA checks a public key to see if it has previously been revoked, this is often done by public key hash, so it is possible that a composite public key is submitted to a CA and even though both component keys have been revoked for key compromise, the CA may not detect it. For this reason, CAs checking composite keys for revocation for key compromise SHOULD check for both component keys independently.

We may already have text to this effect, but we should review it.

**Comment by johngray-dev** [comment]
Requiring fresh keys is what is motivating this security consideration.
