### ISSUE TITLE
PrivateKey section is not explicit about which AlgID OIDs to place in the component OneAsymmetricKeys

### ISSUE THREAD

**Issue by ounsworth** [lamps-wg/draft-composite-sigs#55]
Relates to #6.

If we decide to do the private key compression, then this issue will become moot.

**Comment by johngray-dev** [comment]
The Group agreed to solve #6 so this issue should no longer be relevant.

**Comment by johngray-dev** [comment]
Removing the redundancy from the Private key, so this issue is no longer valid.
