### ISSUE TITLE
Review DER encoding of OIDs

### ISSUE THREAD

**Issue by opencrypto** [lamps-wg/draft-composite-sigs#61]
During the implementation of the new version, the DER encoding value seems to give wrong results for the OID. Here's the binary value that I use in my implementation:
```
0x60, 0x86, 0x48, 0x01, 0x86, 0xFA, 0x6B, 0x50, 0x08, 0x01, 0x01
```
instead of the value in the draft that has a couple of extra bytes.

Am I missing something?

**Comment by johngray-dev** [comment]
The Tag and Length values of the Object ID are in the draft now... Thats the 060B part at the beginning

Plug the ones in the draft in this site:  https://lapo.it/asn1js/
060B6086480186FA6B50080115

It gives the following as an object ID
2.16.840.1.114027.80.8.1.21

We could strip that off if we wanted, and just have the value, which is:
6086480186FA6B50080115

**Comment by ounsworth** [comment]
@opencrypto these are domain separator string, you can just close your eyes and pretend that it's a random hex string. It does not really matter if it can be decoded correctly or not.

**Comment by johngray-dev** [comment]
These aren't really meant to be decoded by software (but they can if you like), that is why we have them in a table for domain separation..
