### ISSUE TITLE
Missing MLDSA44_BrainPool256 from algorithm combinations

### ISSUE THREAD

**Issue by opencrypto** [lamps-wg/draft-composite-sigs#62]
In the latest version of the draft where RSA4096 was added seems to be missing the low-level combination for BrainPool curves (MLDSA44 with BrainPool256R1). Shall it be added back?

**Comment by opencrypto** [comment]
Also the corresponding domain separator is missing.

**Comment by danvangeest** [comment]
Neither BSI nor ANSSI approve MLDSA44 for use.  If I understand correctly, BrainPool is included for them.  So if MLDSA44 with BrainPool256R1 is added I don't think it will be used.

**Comment by janklaussner** [comment]
I agree with @danvangeest, and also look at openpgp wg: https://datatracker.ietf.org/meeting/120/materials/slides-120-openpgp-pqc-with-nist-and-brainpool-curves-00.pdf

**Comment by johngray-dev** [comment]
Based on the comments, I don't think we need this.  We want to align as much with others as possible, and adding another combination means more OIDs and no point adding it unless we know someone that wants this one.

**Comment by johngray-dev** [comment]
Group agreed to close... We will not add this combination
