### ISSUE TITLE
Combination for Level 3 has been changed to (Draft 3) ML_DSA_65 + NISTP384 from (Draft 2) ML_DSA_65 + NISTP256)

### ISSUE THREAD

**Issue by opencrypto** [lamps-wg/draft-composite-sigs#63]
The algorithm mldsa65_p384 is replacing the mldsa64_p256 we had previously. It needs to be reverted back.

**Comment by janklaussner** [comment]
Hi @opencrypto , 
we decided to align the algorithm combinations with the openpgp WG. There ML-DSA-65 is only combined with NISTP384 curves. See the presentation from IETF 120 (https://datatracker.ietf.org/meeting/120/materials/slides-120-openpgp-pqc-with-nist-and-brainpool-curves-00.pdf) As there NIST is engaged in the selection I think the current combination fits best. 
Do YOU explicitely need MLDSA-65 with NISTP256?
